hub.init(function()
  ui.showvalue("Status", FORMAT_SIMPLE, 'Initialized')
  hub.startthread('Main control loop', 4096, function()
    ui.showvalue("IMU Yaw", FORMAT_SIMPLE, imu.value(YAW))
    ui.showvalue("IMU Pitch", FORMAT_SIMPLE, imu.value(PITCH))
    ui.showvalue("IMU Roll", FORMAT_SIMPLE, imu.value(ROLL))
    wait(1000)
  end)
end)
